server:
  port: ${SERVER_PORT:8001}
  forward-headers-strategy: native
  tomcat:
    use-relative-redirects: true
  ssl:
    enabled: true
    key-store: ${KEY-STORE}
    key-store-password: ${KEY-STORE-PASSWORD}
    key-store-type: ${KEY-STORE-TYPE}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true

spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://${DB_HOST_DEV}:${DB_PORT}/${DB_NAME_DEV}
    username: ${DB_USER_DEV}
    password: ${DB_PASSWORD_DEV}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true
  web:
    cors:
      allowed-origins: ${WEB_CORS_ORIGINS}
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false
  http:
    encoding:
      default-encoding: UTF-8

logging:
  level:
    root: info
    mendes:
      dev95: trace
    org:
      springframework:
        web: debug
api:
  security:
    require-https: true
    token:
      secret: ${TOKEN_SECRET} # chave gerada com o comando: "openssl rand -hex 32"
      issuer: ${TOKEN_ISSUER}
cpf:
  api:
    url: ${CPF_API_URL}
    key: ${CPF_API_KEY}

